Update department set manager_id = '2' where dept_code = 'PURCH';
Update department set manager_id = '3' where dept_code = 'ACCTG';
Update department set manager_id = '4' where dept_code = 'MKTGA';
Update department set manager_id = '5' where dept_code = 'SALES';
Update department set manager_id = '6' where dept_code = 'CORFI';
Update department set manager_id = '7' where dept_code = 'LOGIS';
Update department set manager_id = '8' where dept_code = 'ITSUP';
Update department set manager_id = '9' where dept_code = 'HELPD';
Update department set manager_id = '10' where dept_code = 'HR';
Update department set manager_id = '1' where dept_code = 'ADMIN';
commit;