CLEAR COLUMN
COLUMN QUARTER FORMAT A5
SELECT DECODE(TO_NUMBER(TO_CHAR(START_DATE, 'MM')),
	1, 'Q1', 2, 'Q1', 3, 'Q1',
	4, 'Q2', 5, 'Q2', 6, 'Q2',
	7, 'Q3', 8, 'Q3', 9, 'Q3',
	10, 'Q4', 11, 'Q4', 12, 'Q4', 'ERROR') AS QUARTER,
	COUNT(PROJ_NUMBER) "PROJ NUM",
	COUNT(DISTINCT(EMP_NUM)) "EMP NUM",
	SUM(HOURS_USED) "HOURS USED"
FROM PROJECT LEFT OUTER JOIN ASSIGNMENT USING (PROJ_NUMBER)
WHERE TO_NUMBER(TO_CHAR(START_DATE, 'YYYY')) - TO_NUMBER(TO_CHAR(SYSDATE, 'YYYY')) = -1
GROUP BY DECODE(TO_NUMBER(TO_CHAR(START_DATE, 'MM')),
	1, 'Q1', 2, 'Q1', 3, 'Q1',
	4, 'Q2', 5, 'Q2', 6, 'Q2',
	7, 'Q3', 8, 'Q3', 9, 'Q3',
	10, 'Q4', 11, 'Q4', 12, 'Q4', 'ERROR')
ORDER BY QUARTER;
