BREAK ON "EMPLOYEE" ON HIRE_DATE ON "PROJECT NUMBER"
CLEAR COLUMN
COLUMN "EMPLOYEE" FORMAT A30
COLUMN "SKILL" FORMAT A6
COLUMN "TRAINING DATE" FORMAT A13
SELECT EMP_LAST || ' ' || EMP_FIRST "EMPLOYEE", HIRE_DATE,
	CODE "SKILL",
	TO_CHAR(DATE_ACQUIRED) "TRAINING DATE",
	TRUNC(DATE_ACQUIRED - HIRE_DATE) "DAYS AFTER HIRING",
	DECODE(PROJ_NUM, NULL, 0, PROJ_NUM) "PROJECT NUMBER"
FROM EMPLOYEE LEFT OUTER JOIN TRAINING USING (EMP_NUM)
	LEFT OUTER JOIN
	( SELECT EMP_NUM, COUNT(PROJ_NUMBER) AS PROJ_NUM
	FROM ASSIGNMENT LEFT OUTER JOIN PROJECT USING (PROJ_NUMBER)
	GROUP BY EMP_NUM )
	USING (EMP_NUM)
WHERE TO_NUMBER(TO_CHAR(HIRE_DATE, 'YYYY')) - TO_NUMBER(TO_CHAR(SYSDATE, 'YYYY')) = -1;
