--------------------------------------------------------
--  File created - Wednesday-April-16-2014   
--------------------------------------------------------
REM INSERTING into FP.PROJECT
SET DEFINE OFF;
INSERT INTO PROJECT (PROJ_NUMBER, NAME, START_DATE, TOTAL_COST, DEPT_CODE, CLIENT_ID) VALUES (60.0,'Real Estate Appraisal for Hilton Hotels',to_date('06-Dec-12'),439174.0,'ACCTG','8683');
INSERT INTO PROJECT (PROJ_NUMBER, NAME, START_DATE, TOTAL_COST, DEPT_CODE, CLIENT_ID) VALUES (21.0,'Collateral Valuation - BDO',to_date('24-Jan-12'),53333.0,'ACCTG','5062');
INSERT INTO PROJECT (PROJ_NUMBER, NAME, START_DATE, TOTAL_COST, DEPT_CODE, CLIENT_ID) VALUES (64.0,'Work Flow Simulation of Soybean Factory',to_date('01-Mar-13'),198570.0,'OPRTN','5062');
INSERT INTO PROJECT (PROJ_NUMBER, NAME, START_DATE, TOTAL_COST, DEPT_CODE, CLIENT_ID) VALUES (67.0,'Process Efficiency Evaluation for Wearhouse Shirts',to_date('22-Jun-13'),350786.0,'OPRTN','8282');
INSERT INTO PROJECT (PROJ_NUMBER, NAME, START_DATE, TOTAL_COST, DEPT_CODE, CLIENT_ID) VALUES (69.0,'Database Configuration - SSS',to_date('29-Nov-12'),327130.0,'ITSUP','8282');
INSERT INTO PROJECT (PROJ_NUMBER, NAME, START_DATE, TOTAL_COST, DEPT_CODE, CLIENT_ID) VALUES (99.0,'Ratatouille Kiosk and Web Checkin',to_date('07-Jan-13'),313589.0,'ITSUP','8282');
INSERT INTO PROJECT (PROJ_NUMBER, NAME, START_DATE, TOTAL_COST, DEPT_CODE, CLIENT_ID) VALUES (70.0,'Internship and Junior Recruitment',to_date('14-Jul-12'),429374.0,'HR','4379');
INSERT INTO PROJECT (PROJ_NUMBER, NAME, START_DATE, TOTAL_COST, DEPT_CODE, CLIENT_ID) VALUES (16.0,'Anderson Workbench Tool',to_date('01-Jul-13'),400094.0,'HR','5062');
INSERT INTO PROJECT (PROJ_NUMBER, NAME, START_DATE, TOTAL_COST, DEPT_CODE, CLIENT_ID) VALUES (80.0,'Loratadine Maximus',to_date('03-Mar-14'),382475.0,'OPRTN','4379');
INSERT INTO PROJECT (PROJ_NUMBER, NAME, START_DATE, TOTAL_COST, DEPT_CODE, CLIENT_ID) VALUES (81.0,'Automatic Appraisal System',to_date('28-Nov-13'),340603.0,'OPRTN','3541');

--Part D
INSERT INTO PROJECT (PROJ_NUMBER, NAME, START_DATE, TOTAL_COST, DEPT_CODE, CLIENT_ID) VALUES (100.0,'Universal Robina Just In Time Inventory ',to_date('17-Nov-13'),533122.0,'ITSUP','4144');
INSERT INTO PROJECT (PROJ_NUMBER, NAME, START_DATE, TOTAL_COST, DEPT_CODE, CLIENT_ID) VALUES (101.0,'Proctor and Gable Enterprise Resouce Management',to_date('18-Nov-13'),198570.0,'ACCTG','4379');
INSERT INTO PROJECT (PROJ_NUMBER, NAME, START_DATE, TOTAL_COST, DEPT_CODE, CLIENT_ID) VALUES (102.0,'Novare Staff Right Sizing',to_date('19-Nov-13'),350786.0,'HR','6976');
INSERT INTO PROJECT (PROJ_NUMBER, NAME, START_DATE, TOTAL_COST, DEPT_CODE, CLIENT_ID) VALUES (103.0,'Pointwest Technologies Disaster Mangement System',to_date('20-Nov-13'),327130.0,'ACCTG','8579');
INSERT INTO PROJECT (PROJ_NUMBER, NAME, START_DATE, TOTAL_COST, DEPT_CODE, CLIENT_ID) VALUES (104.0,'Champ Cargosystem Lux',to_date('21-Nov-13'),313589.0,'ITSUP','1338');
INSERT INTO PROJECT (PROJ_NUMBER, NAME, START_DATE, TOTAL_COST, DEPT_CODE, CLIENT_ID) VALUES (105.0,'Seven Seven Disaster  Risk Assessment',to_date('22-Nov-13'),429574.0,'ITSUP','3541');
INSERT INTO PROJECT (PROJ_NUMBER, NAME, START_DATE, TOTAL_COST, DEPT_CODE, CLIENT_ID) VALUES (106.0,'Big Pond CMMI Audit',to_date('23-Nov-13'),442094.0,'ITSUP','3035');
INSERT INTO PROJECT (PROJ_NUMBER, NAME, START_DATE, TOTAL_COST, DEPT_CODE, CLIENT_ID) VALUES (107.0,'Navitaire CMMI Audit',to_date('24-Nov-13'),382475.0,'ITSUP','5062');
INSERT INTO PROJECT (PROJ_NUMBER, NAME, START_DATE, TOTAL_COST, DEPT_CODE, CLIENT_ID) VALUES (108.0,'Ayala Technologies Effective Recruitment',to_date('25-Nov-13'),340603.0,'HR','8683');
INSERT INTO PROJECT (PROJ_NUMBER, NAME, START_DATE, TOTAL_COST, DEPT_CODE, CLIENT_ID) VALUES (109.0,'Feasibility Study on Waste Management in Manila',to_date('16-Nov-13'),439374.0,'OPRTN','8282');

--Part B 3
INSERT INTO PROJECT (PROJ_NUMBER, NAME, START_DATE, TOTAL_COST, DEPT_CODE, CLIENT_ID) VALUES (110.0,'AtCMUA Android mobile application development',to_date('01-Jan-14'),null,'ITSUP','4144');
INSERT INTO PROJECT (PROJ_NUMBER, NAME, START_DATE, TOTAL_COST, DEPT_CODE, CLIENT_ID) VALUES (111.0,'Option pricer calculator algorithm design',to_date('08-Mar-14'),null,'ACCTG','4379');
INSERT INTO PROJECT (PROJ_NUMBER, NAME, START_DATE, TOTAL_COST, DEPT_CODE, CLIENT_ID) VALUES (112.0,'Employee satisfication survey',to_date('21-Dec-13'),null,'HR','6976');

--Part B 6
INSERT INTO PROJECT (PROJ_NUMBER, NAME, START_DATE, TOTAL_COST, DEPT_CODE, CLIENT_ID) VALUES (113.0,'Employee satisfication survey',to_date('21-Dec-13'),null,'HR','6976');

commit;
