--------------------------------------------------------
--  File created - Wednesday-April-16-2014   
--------------------------------------------------------
REM INSERTING into FP.PROJECT
SET DEFINE OFF;
INSERT INTO PROJECT (PROJ_NUMBER, NAME, START_DATE, TOTAL_COST, DEPT_CODE, CLIENT_ID) VALUES (60.0,'Real Estate Appraisal for Hilton Hotels',to_date('06-Dec-12'),439174.0,'ACCTG','8683');
INSERT INTO PROJECT (PROJ_NUMBER, NAME, START_DATE, TOTAL_COST, DEPT_CODE, CLIENT_ID) VALUES (21.0,'Collateral Valuation - BDO',to_date('24-Jan-12'),53333.0,'ACCTG','5062');
INSERT INTO PROJECT (PROJ_NUMBER, NAME, START_DATE, TOTAL_COST, DEPT_CODE, CLIENT_ID) VALUES (64.0,'Work Flow Simulation of Soybean Factory',to_date('01-Mar-13'),198570.0,'OPRTN','5062');
INSERT INTO PROJECT (PROJ_NUMBER, NAME, START_DATE, TOTAL_COST, DEPT_CODE, CLIENT_ID) VALUES (67.0,'Process Efficiency Evaluation for Wearhouse Shirts',to_date('22-Jun-13'),350786.0,'OPRTN','8282');
INSERT INTO PROJECT (PROJ_NUMBER, NAME, START_DATE, TOTAL_COST, DEPT_CODE, CLIENT_ID) VALUES (69.0,'Database Configuration - SSS',to_date('29-Nov-12'),327130.0,'ITSUP','8282');
INSERT INTO PROJECT (PROJ_NUMBER, NAME, START_DATE, TOTAL_COST, DEPT_CODE, CLIENT_ID) VALUES (99.0,'Ratatouille Kiosk and Web Checkin',to_date('07-Jan-13'),313589.0,'ITSUP','8282');
INSERT INTO PROJECT (PROJ_NUMBER, NAME, START_DATE, TOTAL_COST, DEPT_CODE, CLIENT_ID) VALUES (70.0,'Internship and Junior Recruitment',to_date('14-Jul-12'),429374.0,'HR','4379');
INSERT INTO PROJECT (PROJ_NUMBER, NAME, START_DATE, TOTAL_COST, DEPT_CODE, CLIENT_ID) VALUES (16.0,'Anderson Workbench Tool',to_date('01-Jul-13'),400094.0,'HR','5062');
INSERT INTO PROJECT (PROJ_NUMBER, NAME, START_DATE, TOTAL_COST, DEPT_CODE, CLIENT_ID) VALUES (80.0,'Loratadine Maximus',to_date('03-Mar-14'),382475.0,'OPRTN','4379');
INSERT INTO PROJECT (PROJ_NUMBER, NAME, START_DATE, TOTAL_COST, DEPT_CODE, CLIENT_ID) VALUES (81.0,'Automatic Appraisal System',to_date('28-Nov-13'),340603.0,'OPRTN','3541');
commit;
