BREAK ON "EMPLOYEE"
CLEAR COLUMN
COLUMN "EMPLOYEE" FORMAT A30
COLUMN "SKILL" FORMAT A10
COLUMN "TIMES" FORMAT A5
COLUMN "RECENT DATE" FORMAT A15
SELECT EMP_NUM || ': ' || EMP_LAST || ' ' || EMP_FIRST "EMPLOYEE",
	CODE "SKILL",
	decode(TO_CHAR(COUNT(CODE)), 0, NULL, TO_CHAR(COUNT(CODE))) "TIMES",
	TO_CHAR(MAX(DATE_ACQUIRED)) "RECENT DATE",
	TRUNC(MONTHS_BETWEEN(SYSDATE, MAX(DATE_ACQUIRED))) "# MONTHS AGO"
FROM EMPLOYEE LEFT OUTER JOIN TRAINING USING (EMP_NUM)
GROUP BY EMP_NUM, EMP_LAST, EMP_FIRST, CODE
ORDER BY EMP_NUM;
CLEAR BREAK COLUMN
