BREAK ON "ONGOING PROJECT NAME" ON START_DATE
CLEAR COLUMN
COLUMN "ONGOING PROJECT NAME" FORMAT A50
COLUMN "MONTH" FORMAT A10
SELECT DECODE(NAME, NULL, 'IN TOTAL', NAME) AS "ONGOING PROJECT NAME", START_DATE,
	TO_CHAR(DATE_ASSIGNED, 'MON-YYYY') "MONTH",
	COUNT(EMP_NUM) "#EMPLOYEES", SUM(HOURS_USED) "TOTAL HOURS"
FROM PROJECT LEFT OUTER JOIN ASSIGNMENT USING (PROJ_NUMBER)
WHERE TOTAL_COST IS NULL
GROUP BY GROUPING SETS ((NAME, START_DATE, TO_CHAR(DATE_ASSIGNED, 'MON-YYYY')), ());
CLEAR BREAK
