--------------------------------------------------------
--  File created - Sunday-April-20-2014   
--------------------------------------------------------
REM INSERTING into HOMER.ASSIGNMENT
SET DEFINE OFF;
Insert into HOMER.ASSIGNMENT (ASSIGN_NUM,PROJ_NUMBER,EMP_NUM,DATE_ASSIGNED,DATE_ENDED,HOURS_USED) values (1,70,15,to_date('22-JUL-13','DD-MON-RR'),to_date('11-DEC-13','DD-MON-RR'),170);
Insert into HOMER.ASSIGNMENT (ASSIGN_NUM,PROJ_NUMBER,EMP_NUM,DATE_ASSIGNED,DATE_ENDED,HOURS_USED) values (2,69,26,to_date('24-JUL-13','DD-MON-RR'),to_date('07-MAR-14','DD-MON-RR'),264);
Insert into HOMER.ASSIGNMENT (ASSIGN_NUM,PROJ_NUMBER,EMP_NUM,DATE_ASSIGNED,DATE_ENDED,HOURS_USED) values (3,67,17,to_date('23-JUL-13','DD-MON-RR'),to_date('17-APR-15','DD-MON-RR'),181);
Insert into HOMER.ASSIGNMENT (ASSIGN_NUM,PROJ_NUMBER,EMP_NUM,DATE_ASSIGNED,DATE_ENDED,HOURS_USED) values (4,70,16,to_date('17-MAY-13','DD-MON-RR'),to_date('03-DEC-13','DD-MON-RR'),178);
Insert into HOMER.ASSIGNMENT (ASSIGN_NUM,PROJ_NUMBER,EMP_NUM,DATE_ASSIGNED,DATE_ENDED,HOURS_USED) values (5,81,30,to_date('28-NOV-13','DD-MON-RR'),to_date('08-SEP-14','DD-MON-RR'),261);
Insert into HOMER.ASSIGNMENT (ASSIGN_NUM,PROJ_NUMBER,EMP_NUM,DATE_ASSIGNED,DATE_ENDED,HOURS_USED) values (6,16,13,to_date('19-DEC-13','DD-MON-RR'),to_date('24-DEC-15','DD-MON-RR'),295);
Insert into HOMER.ASSIGNMENT (ASSIGN_NUM,PROJ_NUMBER,EMP_NUM,DATE_ASSIGNED,DATE_ENDED,HOURS_USED) values (7,16,4,to_date('01-JUL-13','DD-MON-RR'),to_date('06-FEB-14','DD-MON-RR'),202);
Insert into HOMER.ASSIGNMENT (ASSIGN_NUM,PROJ_NUMBER,EMP_NUM,DATE_ASSIGNED,DATE_ENDED,HOURS_USED) values (8,99,9,to_date('07-JAN-13','DD-MON-RR'),to_date('21-SEP-13','DD-MON-RR'),225);
Insert into HOMER.ASSIGNMENT (ASSIGN_NUM,PROJ_NUMBER,EMP_NUM,DATE_ASSIGNED,DATE_ENDED,HOURS_USED) values (9,69,6,to_date('09-OCT-13','DD-MON-RR'),to_date('18-MAR-14','DD-MON-RR'),186);
Insert into HOMER.ASSIGNMENT (ASSIGN_NUM,PROJ_NUMBER,EMP_NUM,DATE_ASSIGNED,DATE_ENDED,HOURS_USED) values (10,64,5,to_date('02-DEC-13','DD-MON-RR'),to_date('22-MAY-14','DD-MON-RR'),33);
Insert into HOMER.ASSIGNMENT (ASSIGN_NUM,PROJ_NUMBER,EMP_NUM,DATE_ASSIGNED,DATE_ENDED,HOURS_USED) values (11,64,30,to_date('03-AUG-13','DD-MON-RR'),to_date('21-DEC-14','DD-MON-RR'),197);
Insert into HOMER.ASSIGNMENT (ASSIGN_NUM,PROJ_NUMBER,EMP_NUM,DATE_ASSIGNED,DATE_ENDED,HOURS_USED) values (12,16,12,to_date('01-JUL-13','DD-MON-RR'),to_date('12-DEC-13','DD-MON-RR'),266);
Insert into HOMER.ASSIGNMENT (ASSIGN_NUM,PROJ_NUMBER,EMP_NUM,DATE_ASSIGNED,DATE_ENDED,HOURS_USED) values (13,70,4,to_date('14-AUG-12','DD-MON-RR'),to_date('08-MAR-13','DD-MON-RR'),53);
Insert into HOMER.ASSIGNMENT (ASSIGN_NUM,PROJ_NUMBER,EMP_NUM,DATE_ASSIGNED,DATE_ENDED,HOURS_USED) values (14,67,17,to_date('22-JUN-13','DD-MON-RR'),to_date('10-JUL-13','DD-MON-RR'),99);
Insert into HOMER.ASSIGNMENT (ASSIGN_NUM,PROJ_NUMBER,EMP_NUM,DATE_ASSIGNED,DATE_ENDED,HOURS_USED) values (15,69,16,to_date('17-JUL-13','DD-MON-RR'),to_date('30-DEC-14','DD-MON-RR'),12);
Insert into HOMER.ASSIGNMENT (ASSIGN_NUM,PROJ_NUMBER,EMP_NUM,DATE_ASSIGNED,DATE_ENDED,HOURS_USED) values (16,80,21,to_date('03-MAR-14','DD-MON-RR'),to_date('04-APR-15','DD-MON-RR'),170);
Insert into HOMER.ASSIGNMENT (ASSIGN_NUM,PROJ_NUMBER,EMP_NUM,DATE_ASSIGNED,DATE_ENDED,HOURS_USED) values (17,99,26,to_date('07-JAN-13','DD-MON-RR'),to_date('27-AUG-13','DD-MON-RR'),22);
Insert into HOMER.ASSIGNMENT (ASSIGN_NUM,PROJ_NUMBER,EMP_NUM,DATE_ASSIGNED,DATE_ENDED,HOURS_USED) values (18,70,7,to_date('17-JAN-13','DD-MON-RR'),to_date('24-JUL-15','DD-MON-RR'),41);
Insert into HOMER.ASSIGNMENT (ASSIGN_NUM,PROJ_NUMBER,EMP_NUM,DATE_ASSIGNED,DATE_ENDED,HOURS_USED) values (19,69,11,to_date('29-NOV-12','DD-MON-RR'),to_date('15-MAR-14','DD-MON-RR'),47);
Insert into HOMER.ASSIGNMENT (ASSIGN_NUM,PROJ_NUMBER,EMP_NUM,DATE_ASSIGNED,DATE_ENDED,HOURS_USED) values (20,60,11,to_date('06-DEC-12','DD-MON-RR'),to_date('15-MAR-14','DD-MON-RR'),47);
Insert into HOMER.ASSIGNMENT (ASSIGN_NUM,PROJ_NUMBER,EMP_NUM,DATE_ASSIGNED,DATE_ENDED,HOURS_USED) values (21,21,12,to_date('24-JAN-12','DD-MON-RR'),to_date('15-MAR-14','DD-MON-RR'),47);
Insert into HOMER.ASSIGNMENT (ASSIGN_NUM,PROJ_NUMBER,EMP_NUM,DATE_ASSIGNED,DATE_ENDED,HOURS_USED) values (22,100,2,to_date('17-NOV-13','DD-MON-RR'),to_date('17-DEC-13','DD-MON-RR'),160);
Insert into HOMER.ASSIGNMENT (ASSIGN_NUM,PROJ_NUMBER,EMP_NUM,DATE_ASSIGNED,DATE_ENDED,HOURS_USED) values (23,100,2,to_date('16-JAN-14','DD-MON-RR'),to_date('15-FEB-14','DD-MON-RR'),160);
Insert into HOMER.ASSIGNMENT (ASSIGN_NUM,PROJ_NUMBER,EMP_NUM,DATE_ASSIGNED,DATE_ENDED,HOURS_USED) values (24,101,3,to_date('18-NOV-13','DD-MON-RR'),to_date('02-JAN-14','DD-MON-RR'),160);
Insert into HOMER.ASSIGNMENT (ASSIGN_NUM,PROJ_NUMBER,EMP_NUM,DATE_ASSIGNED,DATE_ENDED,HOURS_USED) values (25,101,3,to_date('01-FEB-14','DD-MON-RR'),to_date('03-MAR-14','DD-MON-RR'),160);
Insert into HOMER.ASSIGNMENT (ASSIGN_NUM,PROJ_NUMBER,EMP_NUM,DATE_ASSIGNED,DATE_ENDED,HOURS_USED) values (26,102,8,to_date('19-NOV-13','DD-MON-RR'),to_date('03-JAN-14','DD-MON-RR'),160);
Insert into HOMER.ASSIGNMENT (ASSIGN_NUM,PROJ_NUMBER,EMP_NUM,DATE_ASSIGNED,DATE_ENDED,HOURS_USED) values (27,102,8,to_date('02-FEB-14','DD-MON-RR'),to_date('04-MAR-14','DD-MON-RR'),160);
Insert into HOMER.ASSIGNMENT (ASSIGN_NUM,PROJ_NUMBER,EMP_NUM,DATE_ASSIGNED,DATE_ENDED,HOURS_USED) values (28,103,10,to_date('20-NOV-13','DD-MON-RR'),to_date('04-JAN-14','DD-MON-RR'),160);
Insert into HOMER.ASSIGNMENT (ASSIGN_NUM,PROJ_NUMBER,EMP_NUM,DATE_ASSIGNED,DATE_ENDED,HOURS_USED) values (29,103,10,to_date('03-FEB-14','DD-MON-RR'),to_date('05-MAR-14','DD-MON-RR'),160);
Insert into HOMER.ASSIGNMENT (ASSIGN_NUM,PROJ_NUMBER,EMP_NUM,DATE_ASSIGNED,DATE_ENDED,HOURS_USED) values (30,104,14,to_date('21-NOV-13','DD-MON-RR'),to_date('05-JAN-14','DD-MON-RR'),160);
Insert into HOMER.ASSIGNMENT (ASSIGN_NUM,PROJ_NUMBER,EMP_NUM,DATE_ASSIGNED,DATE_ENDED,HOURS_USED) values (31,104,14,to_date('04-FEB-14','DD-MON-RR'),to_date('06-MAR-14','DD-MON-RR'),160);
Insert into HOMER.ASSIGNMENT (ASSIGN_NUM,PROJ_NUMBER,EMP_NUM,DATE_ASSIGNED,DATE_ENDED,HOURS_USED) values (32,105,18,to_date('22-NOV-13','DD-MON-RR'),to_date('06-JAN-14','DD-MON-RR'),160);
Insert into HOMER.ASSIGNMENT (ASSIGN_NUM,PROJ_NUMBER,EMP_NUM,DATE_ASSIGNED,DATE_ENDED,HOURS_USED) values (33,105,18,to_date('05-FEB-14','DD-MON-RR'),to_date('07-MAR-14','DD-MON-RR'),160);
Insert into HOMER.ASSIGNMENT (ASSIGN_NUM,PROJ_NUMBER,EMP_NUM,DATE_ASSIGNED,DATE_ENDED,HOURS_USED) values (34,106,19,to_date('23-NOV-13','DD-MON-RR'),to_date('07-JAN-14','DD-MON-RR'),160);
Insert into HOMER.ASSIGNMENT (ASSIGN_NUM,PROJ_NUMBER,EMP_NUM,DATE_ASSIGNED,DATE_ENDED,HOURS_USED) values (35,106,19,to_date('06-FEB-14','DD-MON-RR'),to_date('08-MAR-14','DD-MON-RR'),160);
Insert into HOMER.ASSIGNMENT (ASSIGN_NUM,PROJ_NUMBER,EMP_NUM,DATE_ASSIGNED,DATE_ENDED,HOURS_USED) values (36,107,20,to_date('24-NOV-13','DD-MON-RR'),to_date('08-JAN-14','DD-MON-RR'),160);
Insert into HOMER.ASSIGNMENT (ASSIGN_NUM,PROJ_NUMBER,EMP_NUM,DATE_ASSIGNED,DATE_ENDED,HOURS_USED) values (37,107,20,to_date('07-FEB-14','DD-MON-RR'),to_date('09-MAR-14','DD-MON-RR'),160);
Insert into HOMER.ASSIGNMENT (ASSIGN_NUM,PROJ_NUMBER,EMP_NUM,DATE_ASSIGNED,DATE_ENDED,HOURS_USED) values (38,108,22,to_date('25-NOV-13','DD-MON-RR'),to_date('09-JAN-14','DD-MON-RR'),160);
Insert into HOMER.ASSIGNMENT (ASSIGN_NUM,PROJ_NUMBER,EMP_NUM,DATE_ASSIGNED,DATE_ENDED,HOURS_USED) values (39,108,22,to_date('08-FEB-14','DD-MON-RR'),to_date('10-MAR-14','DD-MON-RR'),160);
Insert into HOMER.ASSIGNMENT (ASSIGN_NUM,PROJ_NUMBER,EMP_NUM,DATE_ASSIGNED,DATE_ENDED,HOURS_USED) values (40,109,23,to_date('16-NOV-13','DD-MON-RR'),to_date('31-DEC-13','DD-MON-RR'),160);
